- a [[list]].
	- [[gautama buddha]] (IIUC before becoming a "fully fledged" [[buddha]])
	- [[avalokiteshvara]]
	- [[shantideva]]
	- [[samantabhadra]]
	- [[vajrapani]]
	- [[ksitigarbha]]
	- [[akashagarbha]]
	-