- a [[game]].
	- not to be confused with [[braid]].
	- Braid is a solitaire/coop game I think I may have invented.
	- It goes like this:
		- you [[count]], from zero up.
			- I do this while meditating, but that's optional, I guess.
				- Unless we're always meditating?
					- ([[buddha nature]] and all)
		- as you count, you visualize the number.
			- I do a version of [[box breathing]].
				- It helps me reach [[samatha]].
				- as I breathe in, I count up the side of a square 👆
				- as I hold, I traverse a lateral edge ▶
				- as I breathe out, I factorize the number as I go down 👇
				- as I am yet not breathing in, I optionally rest
				-