- a [[course]].
	- #go https://www.capracourse.net
	- sounds amazing! let's see :)
	- #pull [[frijof capra]] [[patterns of connection]] [[systems and cybernetics]]
	- [[spring]]
		- "Welcome to the Capra Course! The lectures will be posted on this page. The first lecture will be released on Wednesday, February 23, 2022, and a new lecture will be released every Wednesday thereafter. By the time the course is completed, there will be 12 lectures released in total."
		- "After the last lecture is released on May 11, 2022, all 12 lectures will be accessible until June 22, 2022. The course will then be closed and alumni will be transferred to our Alumni Network."
		- "Please watch the video for each lecture, read the lecture summary, and then head on over to the Forum for discussion."
		- "You may begin by making connections with other students in the course any time using the forums or by reading the introduction to [[The Systems View of Life]] in preparation for the course."
	- [[forum]] https://spring.capracourse.net/forum/