- on [[2022-05-22]]
	- for [[capra course]]
	- about [[32]] people attending
	- begins with a [[moment of grounding]], 2x [[bell]] (nice) by [[della duncan]]
	- [[fritjof capra]] says:
		- glad to see people face to face, usually enjoy the closing circles tremendously, looking forward to hearing from you
		- taking an opportunity to reflect on the difficult times we're living in, and the transition we're living through.
		- in the last 40 years I have seen technological revolution, backlash -- the turn of the chaotic pendulum
		- [[war in ukraine]] seems to be a regression to the status quo around the 50s-60s
			- grew up tens of miles away from the [[iron curtain]] in [[austria]]
				- the two blocs were in [[competition]]
			- [[bloc thinking]] is making a comeback:
				- [[putin]], who seemingly wants to rebuild the russian empire as it was pre 1989
				- [[nato]], an alliance from [[cold war]] times
				- both blocs are incompatible with the massively interconnected world we live in today
				- our major problems are [[global]] and [[systemic]]
				- we need [[cooperation]], [[negotiation]] and [[compromise]] to solve them, not [[competition]] or [[war]]
				- the outlines of the necessary [[compromise]] in this conflict seem clear:
					- [[putin]] will not get to rebuild imperial russia
					- [[ukraine]] will not get to join [[nato]], but rather remain neutral
			- when dealing with a bully, increasing military tension does not seem a wise path to follow
			- [[cuban missile crisis]] [[1962]] was resolved by [[diplomacy]] and with a compromise
				- [[usa]] withdrew missiles from [[turkey]]
				- [[russia]] withdrew missiles from [[cuba]]
			- hopefully [[diplomacy]] and [[compromise]] will outweigh the [[mechanistic]] bloc thinking from the past
	- [[silvia]]
	-