- on [[2022-05-22]]
	- for [[capra course]]
	- about [[32]] people attending
	- begins with a [[moment of grounding]], 2x [[bell]] (nice) by [[bella]]
	- [[fritjof capra]]:
		- glad to see people face to face, usually enjoy the closing circles tremendously, looking forward to hearing from you
		- taking an opportunity to reflect on the difficult times we're living in, and the transition we're living through.
		- in the last 40 years I have seen
	-