- a [[course]].
	- #go https://www.capracourse.net
	- sounds amazing! let's see :)
	- #pull [[frijof capra]] [[patterns of connection]] [[systems and cybernetics]]
	- [[spring]]
		- "Welcome to the Capra Course! The lectures will be posted on this page. The first lecture will be released on Wednesday, February 23, 2022, and a new lecture will be released every Wednesday thereafter. By the time the course is completed, there will be 12 lectures released in total."
		- "After the last lecture is released on May 11, 2022, all 12 lectures will be accessible until June 22, 2022. The course will then be closed and alumni will be transferred to our Alumni Network."
		- "Please watch the video for each lecture, read the lecture summary, and then head on over to the Forum for discussion."
		- "You may begin by making connections with other students in the course any time using the forums or by reading the introduction to [[The Systems View of Life]] in preparation for the course."
	- [[forum]] https://spring.capracourse.net/forum/
	- [[lecture 1]] [[systems thinking]]
		- introduction
		- [[summary]] https://spring.capracourse.net/wp-content/uploads/2016/06/Lecture-1-Summary.pdf
	- [[lecture 2]] [[the web of life]]
		- [[summary]] https://spring.capracourse.net/wp-content/uploads/2016/06/Lecture-2-Summary.pdf
	- [[lecture 3]] [[order and complexity in the living world]]
		- [[summary]] https://spring.capracourse.net/wp-content/uploads/2021/03/Lecture-3-Summary.pdf
		- complex systems ~ [[non linear systems]]
	- [[lecture 4]] [[the systems view of evolution]]
		- [[summary]]  https://spring.capracourse.net/wp-content/uploads/2021/03/Lecture-4-Summary.pdf
		- [[prebiotic evolution]]
		- [[lipid walls]] acted as proto membranes
			- within simple bubbles that tended to let some compounds selectively in and keep them in, those compounds collisioned and interacted much more often than without
			- yields [[network chemistry]]
		- [[universal ancestor]] is thought to have come into existence around ~3.5B years ago
		- rather than seeing evolution as the result of random mutations, the central focus is on the creativity and the dynamics of life as processes of increasing complexity
		- [[history of evolutionary thought]]
			- #push [[charles darwin]]
				- [[chance variation]] -> [[random mutation]]
				- [[natural selection]]
	- [[lecture 5]]