- a [[book]].
	- [[david bollier]] [[silke helfrich]]
	- on [[commons]]
		- recommended by [[neil]]
		- a [[banger]].
	- [[go]] https://www.freefairandalive.org/read-it
	- [[es]] [[libres, dignos, vivos]]