- a [[paper]].
	- #pull [[harmony seeking computations]]
		- unclear if plural or singular is canonical given that the URL is in singular but the title is in plural :)
	- #go https://www.cs.york.ac.uk/nature/workshop/papers/Harmony-Seeking_Computation.pdf