# j0lms
- a [[person]]
	- [[composer]] [[developer]] [[venezuela]]
	- [[friend]]
	- [[twitter]] https://twitter.com/j0lms
	- [[matrix]] @j0lms:matrix.org
	- [[pull]] [[j0lms]]
	- [[go]] https://jorgeolmos.pythonanywhere.com/
	- told me about [[engels]]
		- [[a fresh new morning has dawned]]
		- [[schelling and revelation]]
- [[2022-03-05]]
	- would like to help people