# Logseq
- a [[pkm tool]]
	- [[roam like]], but didn't set out to be a clone as [[athens]] apparently did
	- by [[tienson qin]], [[junyu zhan]]
	- [[twitter]] https://twitter.com/logseq
	- [[go]] https://logseq.com
	- [[git]] https://github.com/logseq/logseq
		- [[bugs]] https://github.com/logseq/logseq/issues
	- could be a better default [[agora editor]] than [[foam]]
		- easier to use
	- could be a better default [[agora editor]] than [[obsidian]]
		- [[open source]]
			- server components not quite, but coming soon
	- browser based but also offers an [[app]] (electron)
	- based around [[git]], like the [[agora]]
		- can create a repository for you
	- defaults to [[org-mode]] instead of [[markdown]] but they now (as of June 2021) support markdown well
		- uses [[isomorphic git]]
	- [[oauth]] support
	- [[fission]] https://twitter.com/FISSIONcodes/status/1380313842622717953
	- [[2022-05]] raised [[4m]]
    - a bit slow at the ~5k notes range unfortunately. As of [[2022-05-26]] I'm experimenting with using [[wiki vim]] instead, although I do miss some [[logseq]] features.
