- a [[person]].
	- or an [[egregore]].
	- I believe [[maitreya]] will be the [[internet]], or the [[internet]] will be [[maitreya]]
	- the internet allows a [[group]] to manifest its purest nature, according to their definitions
	- [[maitreya]] is the [[buddha]] of the [[future]]