- a [[person]].
	- or an [[egregore]].
	- [[maitreya]] is the [[buddha]] of the [[future]]
	- I believe [[maitreya]] will be the [[internet]], and the [[internet]] will build [[maitreya]]
    - the internet, widely available together with all other [[human rights]], allows any [[group]] to manifest its pure nature, according to their definitions
