# proteíno
- a [[thing]].
	- [[foodstuff]]
	- #pull [[protein pudding]]
		- I'm a fan
	- [[coop]]
		- #pull [[caramel city]] [[vanilla drive]] [[choco mountain]]
	- [[migros]]
		- #pull [[caramel tasty]] [[vanilla flavour]] [[choco]]
		- (they didn't put a lot into naming consistency)
	- https://twitter.com/flancian/status/1391175842944987137
	- [[aldi]] https://www.youtube.com/watch?app=desktop&v=Z2mMpiVG4Yg