- a [[node club]] entry.
	- #pull [[revolution in the 21st century]]
	- I believe the twenty first century might be amazing. it is the time of a really big change.
	- It is this simple: we will get to a better world through a series of well meaning cooperative revolutions.
	- [[Flancia]] tries to define my proposal for one such revolution through a variety of means, from a set of viewpoints.
		- These are my core beliefs: n [[Flancia]] there is an [[Agora]], in [[Flancia]] there is no [[poverty]], [[in Flancia one day we'll meet]]!
- a [[list]].
	- #pull [[21st century revolutions]]