# Revolution
- a [[process]].
	- #pull [[revolutions]]
	- [[political action]] [[disruptive]]
		- ocassionally, but not necessarily in the end, [[disruptive]]?
			- my current best known proposal is the [[flancia revolution]], which is designed to be reasonably all-optional (see below)
	- [[wp]] https://en.wikipedia.org/wiki/Revolution
		- [[quote]] a revolution (Latin: revolutio, "a turn around") is a [[fundamental]] and [[relatively sudden]] change in [[political power]] and political organization which occurs [[when the population revolts against the government]], typically due to perceived [[oppression]] (political, social, economic) or political incompetence.
	- [[aristotle]] describes two types of [[political revolution]]:
		- [[complete change]] from one [[constitution]] to another
		- [[modification]] of an existing constitution.
	- [[pull]] [[hannah arendt]] [[peter singer]] [[satyagraha]] [[frederick engels]]
- Flancia is meant to be a [[loving kindness]] revolution.
	- #push [[revolution in the twenty first century]]
		- I like to think of [[flancia]] as the world as it could be, improved through a series of [[peaceful]] revolutions.
			- [[protopoi]] is the [[space]] of composable [[atomic revolutions]]; rational and well meaning changes for the better.
				- we can [[explore]] this space together, and to do so it is that I set out to build [[an agora]].
				- I am a [[flancian]] and this [[agora]] contains my [[manifesto]].
			- In Flancia they used the [[internet]] to build a global [[commons]].
				- #pull [[knowledge commons]] [[internet]]
	- https://twitter.com/flancian/status/1368252143338192898
	- https://twitter.com/flancian/status/1462091524985045001
- #pull [[internationals]] [[free, fair and alive]] [[patterns]]