# Revolution
- a [[thing]].
	- #pull [[revolutions]]
	- [[political action]] [[disruptive]]
	- ocassionally, but not necessarily in the end, [[disruptive]]
		- my proposal for the revolution is the [[flancian revolution]], which is designed to be reasonably all-optional
	- [[wp]] https://en.wikipedia.org/wiki/Revolution
		- [[quote]] a revolution (Latin: revolutio, "a turn around") is a [[fundamental]] and [[relatively sudden]] change in [[political power]] and political organization which occurs [[when the population revolts against the government]], typically due to perceived [[oppression]] (political, social, economic) or political incompetence.
	- [[aristotle]] describes two types of [[political revolution]]:
		- [[complete change]] from one [[constitution]] to another
		- [[modification]] of an existing constitution.
	- [[pull]] [[hannah arendt]] [[peter singer]] [[satyagraha]]
- Flancia is meant to be a [[loving kindness]] revolution.
	- I like to think of [[flancia]] as the world as it could be, improved through a series of [[peaceful]] revolutions.
		- [[protopoi]] is the [[space]] of composable [[atomic revolutions]]; rational changes for the better.
		- we can [[explore]] it together
	- I am a [[flancian]] and this [[agora]] is meant to be a [[manifesto]].
	- [[pull]] [[fourth international]] [[fifth international]] [[sixth international]]
	- https://twitter.com/flancian/status/1368252143338192898
	- https://twitter.com/flancian/status/1462091524985045001