- a [[node club]] entry.
	- #pull [[revolution in the 21st century]]
	- I believe the twenty first century might be an amazing time to be alive.
		- It seems to me it will be a time of really big changes -- hopefully mostly for the better, in the sense as affecting most people for good.
		- #pull [[timelines]]
			- We will get (we have always gotten) to a better world through a series of well meaning cooperative reforms and revolutions -- those unlocked via solving [[coordination problems]].
- a [[list]].
	- #push [[21st century revolutions]]
		- #pull [[internet revolution]]
		- #pull [[venezuelan revolution]]
		- #pull [[kurdish revolution]]
		- #pull [[russian revolution of 2023]]
		- #pull [[flancian revolution of 2025]]
		- #pull [[international revolution of 2030]]
	- #push [[flancia]]
		- [[Flancia]], in all its shapes, tries to define my proposal for a well meaning revolution -- for common good, through a variety of means, from public viewpoints.
			- These are my core beliefs: [[in Flancia there is no poverty]], [[in Flancia there is an Agora]], [[in Flancia we'll meet]].
		- #pull [[2000s]] [[perhaps naive]]