- a [[node club]] entry.
	- #pull [[revolution in the 21st century]]
	- I believe the twenty first century might be an amazing time to be alive. it is the time of a really big change.
		- It is this simple: we will get (we have always gotten) to a better world through a series of well meaning cooperative revolutions -- those unlocked via solving [[coordination problems]], for example.
- a [[list]].
	- #pull [[21st century revolutions]]
	- [[venezuela]]
	- [[ocalan]]
	- #push [[flancia]]
		- [[Flancia]], in all its shapes, tries to define my proposal for a well meaning revolution -- for common good, through a variety of means, from public viewpoints.
			- These are my core beliefs: [[in Flancia there is no poverty]], [[in Flancia there is an Agora]], [[in Flancia we'll meet]].
		- #pull [[2000s]] [[perhaps naive]]