- a [[tool]].
	- [[timer]].
	- [[install]]
		- ```
		- sudo apt-get install espeak
		- pip3 install termdown
		- ```
	- a tiny shell script I use with it to do [[pomodoro]]:
		- ```
		- alias pomodoro='while true; do termdown -v en 25m -c 10 --font doh -e; termdown -v en 5m -c 10 --font doh -e; done'
		- ```