- [[push]] [[tmux]]
	- [[window]] `<c-b>:resize-window -A`
	- [[pane]] hold `<c-b>` and press arrows
	- [[tmux]] has this annoying habit to always fit to the *smallest* terminal attached to a session, even if inactive.
		- it results in terminals that look like this:
		- ![image.png](./assets/image_1653227629683_0.png)
		- starting after version 2.8 (version 2.8 doesn't have this), you can use