- Users have value for companies, and that's a tricky yet interesting conversation to have: we're talking about [[people with a price in the market]].
	- I don't quite understand why companies don't [[pay users]].
	- [[flanbook]] and [[flanner]] pay back, pay forward!