# xin0
- a [[person]].
	- [[friend]]
	- [[pull]] [[249]]
	- [[meet]] https://meet.google.com/jzw-iamu-ydf
	- [[logseq]] user
	- works in [[startup]]
## [[2021-12-04]]
- how fast to go, how to decide on a tradeoff that balances:
	- how much to focus on producing
	- meditating
	- self love
	- [[tcot]] == our kind [[twitter bubble]]
- [[nick cammarata]]
	- [[jhanas]]
		- [[jhana inflation]]
	- [[andres gomez emilson]]
		- [[qualia computing]]
- [[meditation]] and [[memory]]
- [[flancia]]
	- [[agora]]
- how to make [[an agora]] better
	- would it be better if the agora focused also on finding *mis* aligned values, instead of focusing on shared goals and values?
	- totally!
	- [[agora protocol]], old doc, has some on this
- [[philosophical questions]]
- [[game]] [[humankind]]
- something we could disagree on
	- the role of [[money]]?
		- agreed
	- [[non profit]] vs [[for profit]]
		- less likely to be low hanging fruit in the for profit space
		- to some extent the distinction is unclear if the organization has a good intent (e.g. it will forward profit to good causes)
		- it might be a tax code distinction at root?
- [[democracy]]
	- [[exit, voice and loyalty]]
	-